### ISSUE TITLE
Prevent Yoast from modifying custom RSS feeds (or allow a publisher to)

### ISSUE THREAD

**Issue by avcascade** [Automattic/newspack-rss-enhancements#1]
Yoast SEO has a default setting (which can be customized or turned off, but is usually left on) that allows publishers to append and prepend content in RSS feeds. [The feature is described here](https://yoast.com/help/how-to-use-rss-variables-in-yoast-seo/), and it can be seen in action on pretty much any Newspack publisher's site. This is ordinarily a useful feature because it can mitigate problems associated with the copying (some would say _theft_) of content. However, it's potentially undesirable in a custom RSS feed that is being used for sharing content internally between sites owned by a publisher, or between a publisher and their partners, such as those created by this plugin. Yoast doesn't have an option to only enable RSS feed modifications on the main feed or on default, guessable feed URLs in general. It would be helpful if Newspack RSS Enhancements could either prevent these modifications or provide a switch allowing a publisher to prevent them.

**Comment by claudiulodro** [comment]
Implemented in https://github.com/Automattic/newspack-rss-enhancements/pull/3
