### ISSUE TITLE
Wrong version information for v0.3.0 download

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-rss-enhancements#11]
Looks like [v0.3.0 files](https://github.com/Automattic/newspack-rss-enhancements/tree/0.3.0), doesn't include https://github.com/Automattic/newspack-rss-enhancements/commit/48e787b75d15f79c18d01a57f31c12a40f85e0f7 commit and it results in version shows as 0.2.1

**Comment by adekbadek** [comment]
Closing, this code has been moved to [`newspack-plugin`](https://github.com/Automattic/newspack-plugin/).
